### ISSUE TITLE
Unsupported value 20002 has been returned for <enum 'FailureType'>

### ISSUE THREAD

**Issue by RichieB2B** [iMicknl/python-overkiz-api#981] opened 2023-09-20 20:58 UTC
I received 60 of these warnings this morning. They were two in a row. The two minutes gap is caused by a sleep from my app.
```
Sep 20 08:07:48 nasty python3[3163548]: WARNING:pyoverkiz.enums.general:Unsupported value 20002 has been returned for <enum 'FailureType'>
Sep 20 08:07:48 nasty python3[3163548]: WARNING:pyoverkiz.enums.general:Unsupported value 20002 has been returned for <enum 'FailureType'>
Sep 20 08:09:49 nasty python3[3163548]: WARNING:pyoverkiz.enums.general:Unsupported value 20002 has been returned for <enum 'FailureType'>
Sep 20 08:09:49 nasty python3[3163548]: WARNING:pyoverkiz.enums.general:Unsupported value 20002 has been returned for <enum 'FailureType'>
```
Unfortunately I don't have any more context. The API seemed to be working fine and my app was retrieving data from the `atalantic-cozytouch` server as usual. Looking at the timing of the warnings it is either caused by `client.execute_command()` or `client.get_state()`.

**Comment by iMicknl** [comment] 2023-09-27 20:08
This is caused by an update to the CozyTouch API / server. Will be fixed in an upcoming release.

**Closed** 2023-09-27 20:09 UTC
